// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzxuqxfnxdvbqkxehnou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eHVxeGZueGR2YnFreGVobm91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NzI1ODksImV4cCI6MjA3MDE0ODU4OX0.SVm6l_il4iNFkGqGvRsAJwAeEDc7adMCg4X0l9Zf8Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});